#!/bin/bash
#
# equivalent to sed -n 'G; s/\n/&&/; /^\([ -~]*\n\).*\n\1/d; s/\n//; h; P'
#
awk '!a[$0]++' "$@"
## Efficient way ? Empty statement "a[$0]" creates an element in the array.
#awk '!($0 in a) { a[$0]; print }' "$@"
